ALTER TABLE deliverers ADD COLUMN IF NOT EXISTS needs_onboarding BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE stores     ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE stores     ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
